# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gen_proto_types.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15gen_proto_types.proto\x12\rprotei.uc.api\"(\n\x17GeneralRequestWithToken\x12\r\n\x05token\x18\x01 \x01(\t\"f\n\x0fGeneralResponse\x12.\n\x0bresult_code\x18\x01 \x01(\x0e\x32\x19.protei.uc.api.ResultCode\x12#\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x14.protei.uc.api.Error\"A\n\x05\x45rror\x12\x0e\n\x06reason\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x0f\n\x07\x63ommand\x18\x03 \x01(\t:\x02\x18\x01*\xe9\x03\n\nResultCode\x12\n\n\x02OK\x10\x00\x1a\x02\x08\x01\x12\x1b\n\x13INVALID_CREDENTIALS\x10\x01\x1a\x02\x08\x01\x12\x0e\n\x06\x42\x41\x44\x41RG\x10\x02\x1a\x02\x08\x01\x12\x14\n\x0cPCONNREFUSED\x10\x03\x1a\x02\x08\x01\x12\x11\n\tNOT_FOUND\x10\x04\x1a\x02\x08\x01\x12\x1b\n\x13\x44\x42_CONNECTION_ERROR\x10\x05\x1a\x02\x08\x01\x12\x14\n\x0cSYNTAX_ERROR\x10\x06\x1a\x02\x08\x01\x12\x15\n\rUNKNOWN_ERROR\x10\x07\x1a\x02\x08\x01\x12\x16\n\x0e\x41LREADY_EXISTS\x10\x08\x1a\x02\x08\x01\x12\x16\n\x0eUSER_NOT_FOUND\x10\t\x1a\x02\x08\x01\x12\x17\n\x0fPARTIAL_SUCCESS\x10\n\x1a\x02\x08\x01\x12\x16\n\x0e\x43HAT_NOT_FOUND\x10\x0b\x1a\x02\x08\x01\x12\x0f\n\x07\x43REATED\x10\x0c\x1a\x02\x08\x01\x12\x17\n\x0fNOT_IMPLEMENTED\x10\r\x1a\x02\x08\x01\x12\x11\n\tFORBIDDEN\x10\x0e\x1a\x02\x08\x01\x12\x16\n\x0eNOT_CONFIGURED\x10\x0f\x1a\x02\x08\x01\x12\x16\n\x0eNOT_REGISTERED\x10\x10\x1a\x02\x08\x01\x12\x16\n\x0e\x43\x41LL_NOT_FOUND\x10\x11\x1a\x02\x08\x01\x12\x1b\n\x13REGISTRATION_FAILED\x10\x12\x1a\x02\x08\x01\x12\x12\n\nGRPC_ERROR\x10\x13\x1a\x02\x08\x01\x12\x14\n\x0cUSER_DELETED\x10\x14\x1a\x02\x08\x01\x1a\x02\x18\x01\x42\x0eZ\x0c\x61pi/grpc;apib\x06proto3')

_RESULTCODE = DESCRIPTOR.enum_types_by_name['ResultCode']
ResultCode = enum_type_wrapper.EnumTypeWrapper(_RESULTCODE)
OK = 0
INVALID_CREDENTIALS = 1
BADARG = 2
PCONNREFUSED = 3
NOT_FOUND = 4
DB_CONNECTION_ERROR = 5
SYNTAX_ERROR = 6
UNKNOWN_ERROR = 7
ALREADY_EXISTS = 8
USER_NOT_FOUND = 9
PARTIAL_SUCCESS = 10
CHAT_NOT_FOUND = 11
CREATED = 12
NOT_IMPLEMENTED = 13
FORBIDDEN = 14
NOT_CONFIGURED = 15
NOT_REGISTERED = 16
CALL_NOT_FOUND = 17
REGISTRATION_FAILED = 18
GRPC_ERROR = 19
USER_DELETED = 20


_GENERALREQUESTWITHTOKEN = DESCRIPTOR.message_types_by_name['GeneralRequestWithToken']
_GENERALRESPONSE = DESCRIPTOR.message_types_by_name['GeneralResponse']
_ERROR = DESCRIPTOR.message_types_by_name['Error']
GeneralRequestWithToken = _reflection.GeneratedProtocolMessageType('GeneralRequestWithToken', (_message.Message,), {
  'DESCRIPTOR' : _GENERALREQUESTWITHTOKEN,
  '__module__' : 'gen_proto_types_pb2'
  # @@protoc_insertion_point(class_scope:protei.uc.api.GeneralRequestWithToken)
  })
_sym_db.RegisterMessage(GeneralRequestWithToken)

GeneralResponse = _reflection.GeneratedProtocolMessageType('GeneralResponse', (_message.Message,), {
  'DESCRIPTOR' : _GENERALRESPONSE,
  '__module__' : 'gen_proto_types_pb2'
  # @@protoc_insertion_point(class_scope:protei.uc.api.GeneralResponse)
  })
_sym_db.RegisterMessage(GeneralResponse)

Error = _reflection.GeneratedProtocolMessageType('Error', (_message.Message,), {
  'DESCRIPTOR' : _ERROR,
  '__module__' : 'gen_proto_types_pb2'
  # @@protoc_insertion_point(class_scope:protei.uc.api.Error)
  })
_sym_db.RegisterMessage(Error)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\014api/grpc;api'
  _RESULTCODE._options = None
  _RESULTCODE._serialized_options = b'\030\001'
  _RESULTCODE.values_by_name["OK"]._options = None
  _RESULTCODE.values_by_name["OK"]._serialized_options = b'\010\001'
  _RESULTCODE.values_by_name["INVALID_CREDENTIALS"]._options = None
  _RESULTCODE.values_by_name["INVALID_CREDENTIALS"]._serialized_options = b'\010\001'
  _RESULTCODE.values_by_name["BADARG"]._options = None
  _RESULTCODE.values_by_name["BADARG"]._serialized_options = b'\010\001'
  _RESULTCODE.values_by_name["PCONNREFUSED"]._options = None
  _RESULTCODE.values_by_name["PCONNREFUSED"]._serialized_options = b'\010\001'
  _RESULTCODE.values_by_name["NOT_FOUND"]._options = None
  _RESULTCODE.values_by_name["NOT_FOUND"]._serialized_options = b'\010\001'
  _RESULTCODE.values_by_name["DB_CONNECTION_ERROR"]._options = None
  _RESULTCODE.values_by_name["DB_CONNECTION_ERROR"]._serialized_options = b'\010\001'
  _RESULTCODE.values_by_name["SYNTAX_ERROR"]._options = None
  _RESULTCODE.values_by_name["SYNTAX_ERROR"]._serialized_options = b'\010\001'
  _RESULTCODE.values_by_name["UNKNOWN_ERROR"]._options = None
  _RESULTCODE.values_by_name["UNKNOWN_ERROR"]._serialized_options = b'\010\001'
  _RESULTCODE.values_by_name["ALREADY_EXISTS"]._options = None
  _RESULTCODE.values_by_name["ALREADY_EXISTS"]._serialized_options = b'\010\001'
  _RESULTCODE.values_by_name["USER_NOT_FOUND"]._options = None
  _RESULTCODE.values_by_name["USER_NOT_FOUND"]._serialized_options = b'\010\001'
  _RESULTCODE.values_by_name["PARTIAL_SUCCESS"]._options = None
  _RESULTCODE.values_by_name["PARTIAL_SUCCESS"]._serialized_options = b'\010\001'
  _RESULTCODE.values_by_name["CHAT_NOT_FOUND"]._options = None
  _RESULTCODE.values_by_name["CHAT_NOT_FOUND"]._serialized_options = b'\010\001'
  _RESULTCODE.values_by_name["CREATED"]._options = None
  _RESULTCODE.values_by_name["CREATED"]._serialized_options = b'\010\001'
  _RESULTCODE.values_by_name["NOT_IMPLEMENTED"]._options = None
  _RESULTCODE.values_by_name["NOT_IMPLEMENTED"]._serialized_options = b'\010\001'
  _RESULTCODE.values_by_name["FORBIDDEN"]._options = None
  _RESULTCODE.values_by_name["FORBIDDEN"]._serialized_options = b'\010\001'
  _RESULTCODE.values_by_name["NOT_CONFIGURED"]._options = None
  _RESULTCODE.values_by_name["NOT_CONFIGURED"]._serialized_options = b'\010\001'
  _RESULTCODE.values_by_name["NOT_REGISTERED"]._options = None
  _RESULTCODE.values_by_name["NOT_REGISTERED"]._serialized_options = b'\010\001'
  _RESULTCODE.values_by_name["CALL_NOT_FOUND"]._options = None
  _RESULTCODE.values_by_name["CALL_NOT_FOUND"]._serialized_options = b'\010\001'
  _RESULTCODE.values_by_name["REGISTRATION_FAILED"]._options = None
  _RESULTCODE.values_by_name["REGISTRATION_FAILED"]._serialized_options = b'\010\001'
  _RESULTCODE.values_by_name["GRPC_ERROR"]._options = None
  _RESULTCODE.values_by_name["GRPC_ERROR"]._serialized_options = b'\010\001'
  _RESULTCODE.values_by_name["USER_DELETED"]._options = None
  _RESULTCODE.values_by_name["USER_DELETED"]._serialized_options = b'\010\001'
  _ERROR._options = None
  _ERROR._serialized_options = b'\030\001'
  _RESULTCODE._serialized_start=254
  _RESULTCODE._serialized_end=743
  _GENERALREQUESTWITHTOKEN._serialized_start=40
  _GENERALREQUESTWITHTOKEN._serialized_end=80
  _GENERALRESPONSE._serialized_start=82
  _GENERALRESPONSE._serialized_end=184
  _ERROR._serialized_start=186
  _ERROR._serialized_end=251
# @@protoc_insertion_point(module_scope)
