# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protei_kv_options.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17protei_kv_options.proto\x12\x13protei.uc.api.types\"\x82\x01\n\x0fProteiKVOptions\x12@\n\x06values\x18\x01 \x03(\x0b\x32\x30.protei.uc.api.types.ProteiKVOptions.ValuesEntry\x1a-\n\x0bValuesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\x45ZCgit.protei.ru/uc/core/services/golang/protei-options;protei_optionsb\x06proto3')



_PROTEIKVOPTIONS = DESCRIPTOR.message_types_by_name['ProteiKVOptions']
_PROTEIKVOPTIONS_VALUESENTRY = _PROTEIKVOPTIONS.nested_types_by_name['ValuesEntry']
ProteiKVOptions = _reflection.GeneratedProtocolMessageType('ProteiKVOptions', (_message.Message,), {

  'ValuesEntry' : _reflection.GeneratedProtocolMessageType('ValuesEntry', (_message.Message,), {
    'DESCRIPTOR' : _PROTEIKVOPTIONS_VALUESENTRY,
    '__module__' : 'protei_kv_options_pb2'
    # @@protoc_insertion_point(class_scope:protei.uc.api.types.ProteiKVOptions.ValuesEntry)
    })
  ,
  'DESCRIPTOR' : _PROTEIKVOPTIONS,
  '__module__' : 'protei_kv_options_pb2'
  # @@protoc_insertion_point(class_scope:protei.uc.api.types.ProteiKVOptions)
  })
_sym_db.RegisterMessage(ProteiKVOptions)
_sym_db.RegisterMessage(ProteiKVOptions.ValuesEntry)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'ZCgit.protei.ru/uc/core/services/golang/protei-options;protei_options'
  _PROTEIKVOPTIONS_VALUESENTRY._options = None
  _PROTEIKVOPTIONS_VALUESENTRY._serialized_options = b'8\001'
  _PROTEIKVOPTIONS._serialized_start=49
  _PROTEIKVOPTIONS._serialized_end=179
  _PROTEIKVOPTIONS_VALUESENTRY._serialized_start=134
  _PROTEIKVOPTIONS_VALUESENTRY._serialized_end=179
# @@protoc_insertion_point(module_scope)
